config/routes.rb
Rails.application.routes.draw do
  root "albums#index"
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  get "/albums", to: "albums#index"
  get "/albums/new", to: "albums#new"
  post "/albums", to: "albums#create"
  get "/albums/:id/edit", to: "albums#edit"
  put "/albums/:id", to: "albums#update"
  patch "/albums/:id", to: "albums#update"
  get "/albums/:id", to: "albums#show"
  delete "/albums/:id", to: "albums#destroy"

  get "/albums/:album_id/photos/new", to: "photos#new"
  post "/albums/:album_id/photos", to: 'photos#create'
  get "/albums/:album_id/photos/:id/edit", to: 'photos#edit'
  put "/albums/:album_id/photos/:id", to: "photos#update"
  patch "/albums/:album_id/photos/:id", to: "photos#update"
  get "/albums/:album_id/photos/:id", to: "photos#show"
  delete "/albums/:album_id/photos/:id", to: "photos#destroy"

  post "/albums/:album_id/photos/:photo_id/comments", to: 'comments#create'
  get "/albums/:album_id/photos/:photo_id/comments/:id/edit", to: 'comments#edit'
  put "/albums/:album_id/photos/:photo_id/comments/:id", to: 'comments#update'
  patch "/albums/:album_id/photos/:photo_id/comments/:id", to: 'comments#update'
  delete "/albums/:album_id/photos/:photo_id/comments/:id", to: 'comments#destroy'
end

app/models/album.rb
class Album < ApplicationRecord
  has_many_attached :images
   has_many :photos
  validates :name, presence: true
  validates :description, presence: true
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_one_attached :image
  belongs_to :album
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :username, presence: true
  validates :age, presence: true
  has_many :albums

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :lockable, :trackable
  INTEREST_FIELD = ['Wedding', 'Events', 'Potraits']
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_album, only: [:show, :edit, :update, :destroy]

  def index
    @albums = Album.where(user_id: current_user.id)
  end

  def new
    @album = Album.new
  end

  def create
     @album = Album.new(album_params)
     @album.user_id = current_user.id
    if @album.save
      redirect_to "/albums/#{@album.id}"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show; end

  def edit;end

  def update
    if @album.update(album_params)
      redirect_to "/albums/#{@album.id}"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @album.destroy
    redirect_to root_path, status: :see_other
  end

   private
   def find_album
     @album = Album.find(params[:id])
   end

   def album_params
     params.require(:album).permit(:name, :description, :images, :caption)
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :confirgure_permitted_parameters, if: :devise_controller?

  protected

  def confirgure_permitted_parameters
    if action_name == 'create'
      devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:email, :password, :password_confirmation, :username, :age,:interests)}
    elsif action_name == 'update'
     devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:email, :password, :password_confirmation, :current_password, :username, :age, :interests)}
   end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

   def create
     @album = Album.find(params[:album_id])
     @photo= Photo.find(params[:photo_id])
     @comment = @photo.comments.create(comment_params)
     redirect_to "/albums/#{@album.id}/photos/#{@photo.id}"
   end

   def edit
      @album = Album.find(params[:album_id])
      @photo = Photo.find(params[:photo_id])
      @comment = Comment.find(params[:id])
   end

   def update
      @album = Album.find(params[:album_id])
      @photo = Photo.find(params[:photo_id])
      @comment = Comment.find(params[:id])
      if @comment.update(comment_params)
        redirect_to  "/albums/#{@album.id}/photos/#{@photo.id}" 
      else
        render :edit, status: :unprocessable_entity
      end
   end

   def destroy
     @album = Album.find(params[:album_id])
     @photo= Photo.find(params[:photo_id])
     @comment = Comment.find(params[:id])
     @comment.destroy
     redirect_to "/albums/#{@album.id}/photos/#{@photo.id}", status: :see_other
   end

   private
     def comment_params
       params.require(:comment).permit(:commenter, :body)
     end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!
  before_action :find_album_object, only: [:new, :show, :create, :edit, :update, :destroy]
  before_action :find_photo_object, only: [ :show, :edit, :update, :destroy]


  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new

  end

  def show; end

  def create
    @photo = @album.photos.create(photo_params)
    redirect_to  "/albums/#{@album.id}"
  end

  def edit; end

  def update
    if @photo.update(photo_params)
      redirect_to "/albums/#{@album.id}"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @photo.destroy
    redirect_to "/albums/#{@album.id}", status: :see_other
  end

  private
  def find_album_object
    @album = Album.find(params[:album_id])
  end

  def find_photo_object
    @photo = Photo.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:image, :caption)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_form.html.erb
<%= form_with  model: album, id: "album_form",  url: url do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% album.errors.full_messages_for(:name).each do |message| %>
      <div  id="name_error"><%= message %></div>
    <% end %>
  </div>

  <div >
    <%= form.label :description %><br>
    <%= form.text_area :description %>
    <% album.errors.full_messages_for(:description).each do |message| %>
    <div id="description_error"><%= message %></div>
  <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Edit Album</h1>

<%= render "form", url: "/albums/#{@album.id}", album: @album %>

app/views/albums/index.html.erb
<% if user_signed_in? %>
  <h1>Hello, <%= current_user.username.capitalize %> </h1>
  <h1>Welcome to 500px </h1>
<% end %>

<h1> Albums: </h1>
<ul id= "albums">
  <% @albums.each do |album| %>
    <li>
       <a href="/albums/<%= album.id %>">
        <%= album.name %>
       </li>
  <% end %>
</ul>
<a href="/albums/new">Add new album</a>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render "form", album: @album, url: "/albums" %>

app/views/albums/show.html.erb
<h1  id= "aname"><%= @album.name%></h1>

<p><%= @album.description %></p>
<ul>
  <li><%= link_to "Edit Album", "/albums/#{@album.id}/edit"%></li>
  <li><%= link_to "Delete Album","/albums/#{@album.id}", data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
  <li><%=link_to "add photos", "/albums/#{@album.id}/photos/new"%></li>
</ul>

<% @album.photos.each do |photo|%>
  <%= image_tag(photo.image, size: "400x400") %></a>
  <li><%= link_to "view", "/albums/#{@album.id}/photos/#{photo.id}"%></li>
  <li><%= link_to "Edit Photo", "/albums/#{@album.id}/photos/#{photo.id}/edit"%></li>
  <li><%= link_to "Delete Photo", "/albums/#{@album.id}/photos/#{photo.id}", data: {
                   turbo_method: :delete,
                   turbo_confirm: "Are you sure?"
                 } %></li>
<%end%>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<li><%= link_to "Edit", "/albums/#{@album.id}/photos/#{@photo.id}/comments/#{comment.id}/edit"%></li>
<li><%= link_to "Destroy","/albums/#{@album.id}/photos/#{@photo.id}/comments/#{comment.id}", data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                }%></li>

app/views/comments/_form.html.erb
<%= form_with model: @photo.comments.build, url:"/albums/#{@album.id}/photos/#{@photo.id}/comments" do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit comment</h1>
<%= form_with model: @comment, url: "/albums/#{@album.id}/photos/#{@photo.id}/comments/#{@comment.id}" do |form| %>
  <div>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
    <% @comment.errors.full_messages_for(:commenter).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% @comment.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoAlbum</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>


  <body>
    <div class="container">
      <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
          <li><%= link_to "Home", root_path, class: 'nav-link px-2 link-secondary' %></li>
          <li><%= link_to "Albums", albums_path, class: 'nav-link px-2 link-dark' %></li>
        </ul>

        <div class="col-md-3 text-end">
          <% if user_signed_in? %>
            <%= link_to "Edit profile", edit_user_registration_path, class: 'btn btn-primary' %>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger me-2' %>
          <% else %>
            <%= link_to "Login", new_user_session_path, class: 'btn btn-outline-primary me-2' %>
            <%= link_to "Sign-up", new_user_registration_path, class: 'btn btn-primary' %>
          <% end %>
        </div>
      </header>
      <%= yield %>
    </div>
  </body>
</html>

app/views/photos/_form.html.erb
<%#= image_tag photo.image %>
<%= form_with model: photo, id:"photo_form", url: "/albums/#{@album.id}/photos/#{photo.id}" do |form| %>
  <div>
    <%= form.label :image %>
    <%= form.file_field :image %>
    <% photo.errors.full_messages_for(:image).each do |message| %>
    <div><%= meassage%></div>
    <%end%>
  </div>
  <div>
    <%= form.label :caption %>
    <%= form.text_field :caption %>
    <% photo.errors.full_messages_for(:caption).each do |message| %>
    <div><%= meassage%></div>
    <%end%>
  </div>

  <div>
    <%= form.submit %>
  </div>
  <% end %>

app/views/photos/edit.html.erb
<h1>Edit Photos</h1>

<%= render "form", url: "/albums/#{@album.id}/photos", photo: @photo %>

app/views/photos/new.html.erb
<%= form_with model: @photo, id:"photo_form", url: "/albums/#{@album.id}/photos" do |form| %>
  <div>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div id="caption">
    <%= form.label :caption %>
    <%= form.text_area :caption%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/show.html.erb
<% @album.photos.each do |photo|%>
  <%= image_tag(photo.image, size: "400x400", id: "my_image") %></a>
    <li><%= link_to "update", "/albums/#{@album.id}/photos/#{photo.id}/edit"%></li>
<p>
  <strong>Caption:</strong>
  <%= photo.caption%>
</p>

<h2>Comments</h2>
<%= render @photo.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<% end %>